import os

# name of files to compile
paper = '{{cookiecutter.paper_name}}'
pdfOpener = Builder(action = 'open -a {{cookiecutter.pdf_app}} $SOURCE', src_suffix = '.pdf')

{% raw %}
env =       Environment(ENV = os.environ)
env['ENV']['TEXINPUTS'] = '.'  # colon separated list
targets =   [os.path.splitext(f)[0] for f in os.listdir('.') if os.path.splitext(f)[1] == '.tex']

env.Append(BUILDERS = {'PDFOpen': pdfOpener})

# Use synctex
env.AppendUnique(PDFLATEXFLAGS='-synctex=1')

Help("""
This is a generic pdfLaTeX builder.
Available targets in this directory:\n
""")

# only open the thesis

for tgt in targets:
    env.Alias(tgt, env.PDFOpen(env.PDF(source = tgt + '.tex')))
    Help('    scons [-c] ' + str(tgt) + '\n')
Help('    scons -c   (to clean all targets)\n')

Default(paper)
{% endraw %}
